# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Node.js app to Azure Web App: doozerpricingcalculatorv1'

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    
    - name: npm install
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Build (type check and bundle)
      run: npm run build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'doozerpricingcalculatorv1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0a3d86e1d430486599236bb599c155fe }}
        package: .
